application:
  name: another-qovery-app
  project: another-qovery-app
  organization: QoveryCommunity
databases:
- type: postgresql
  version: "12"
  name: my-db
routers:
- name: main
  custom_domains:
  - branch: main
    domain: qovery-test1.ledez.net
  routes:
  - application_name: another-qovery-app
    paths:
    - /
