application:
  name: another-qovery-app
  project: another-qovery-app
  organization: QoveryCommunity
databases:
- type: postgresql
  version: "12"
  name: my-db
routers:
- name: main
  routes:
  - application_name: another-qovery-app
    paths:
    - /
